// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:autodoc/config/secrets.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: AppSecrets.firebaseWebApiKey,
    appId: AppSecrets.firebaseAppIdWeb,
    messagingSenderId: AppSecrets.firebaseMessagingSenderId,
    projectId: AppSecrets.firebaseProjectId,
    authDomain: AppSecrets.firebaseAuthDomain,
    databaseURL: AppSecrets.firebaseDatabaseUrl,
    storageBucket: AppSecrets.firebaseStorageBucket,
    measurementId: AppSecrets.firebaseMeasurementId,
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: AppSecrets.firebaseAndroidApiKey,
    appId: AppSecrets.firebaseAppIdAndroid,
    messagingSenderId: AppSecrets.firebaseMessagingSenderId,
    projectId: AppSecrets.firebaseProjectId,
    databaseURL: AppSecrets.firebaseDatabaseUrl,
    storageBucket: AppSecrets.firebaseStorageBucket,
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: AppSecrets.firebaseIosApiKey,
    appId: AppSecrets.firebaseAppIdIos,
    messagingSenderId: AppSecrets.firebaseMessagingSenderId,
    projectId: AppSecrets.firebaseProjectId,
    databaseURL: AppSecrets.firebaseDatabaseUrl,
    storageBucket: AppSecrets.firebaseStorageBucket,
    iosClientId: AppSecrets.firebaseIosClientId,
    iosBundleId: AppSecrets.firebaseIosBundleId,
  );
}
